### ISSUE TITLE
Iterate over points in KDTree

### ISSUE THREAD

**Issue by clbarnes** [enlightware/nabo-rs#2]
Our use case is comparing point clouds to each other, so it's useful to be able to iterate through the points of one to query against the other.

**Comment by stephanemagnenat** [comment]
I am not sure what is the problem. It is trivial at the moment to iterate over the points of one cloud and query it against the other, just call `query` once per point. You can put it in a [rayon](https://crates.io/crates/rayon) for loop to add multi-threading. But maybe I misunderstand your issue?

**Comment by clbarnes** [comment]
Ignore the querying against another bit, that's just our use case.

How can you iterate over the points contained in a tree? I can't see any such functionality in the docs.

**Comment by clbarnes** [comment]
I think this is all it needs:

```rs
struct KDTree ... {
    ...

    pub fn iter(&self) -> impl Iterator<Item = (u32, P)> + '_ {
        self.indices
            .iter()
            .zip(self.points.as_slice().chunks(P::DIM as usize))
            .map(|(idx, x)| {
                let mut p = P::default();
                for (d, v) in x.iter().enumerate() {
                    p.set(d as u32, *v);
                }
                (*idx, p)
            })
    }
}
```
